services:
  db:
    image: bitnami/postgresql:latest
    container_name: hojeafestaenossa_db
    environment:
      POSTGRES_DB: hojeafestaenossa
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: